[
  {
    "CategoryName": "UserAuthenticationError",
    "Types": [
      {
        "TypeName": "CredentialsError",
        "Exceptions": [
          {
            "ExceptionName": "SnowflakeSQLException",
            "MessageRegex": "username|password"
          }, //External Library
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "username|password|GSSAPI credentials|kerberos.*is not valid|A 'Secure Connect' or a Kerberos connection can't be built outside of a user call"
          }, // username-password external. kerberos.*is not valid - alloy. A 'Secure Connect' or a Kerberos connection can't be built - engine
          {
            "ExceptionName": "UnsupportedOperationException",
            "MessageRegex": "Kerberos|credential"
          }, //legend-engine
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "bad credentials|does not contain one of the expected credential types|Identity does not contain one of the expected credential types|Failed to authenticate to kerberos|Error getting SecureConnect credentials from|Cannot build cookie store."
          }, //cookie store, identity does not contain.. and secureconnect is alloy, bad credentials and failed to authenticate kerberos are external
          {
            "ExceptionName": "LoginException",
            "MessageRegex": ""
          }, //alloy
          {
            "ExceptionName": "GSSException",
            "MessageRegex": "No valid credentials provided|defective token detected"
          }, //external
          {
            "ExceptionName": "SQLException",
            "MessageRegex": "Expired SecureConnect token|GSSException is caught when getting a ticket from JGSS|Invalid user ID or password"
          }, //external
          {
            "ExceptionName": "SQLInvalidAuthorizationSpecException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "PoolInitializationException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Failed to initialize pool"
          }, //external but some engine test includes this exact message for snowflake exception
          {
            "ExceptionName": "AuthenticationFailedException",
            "MessageRegex": "401 Unauthorized"
          }, //external
          {
            "ExceptionName": "IOException",
            "MessageRegex": "Server returned HTTP response code: 401 for URL"
          }, //external
          {
            "ExceptionName": "Exception",
            "MessageRegex": "Identity does not contain [one of the ]?expected credential type[s]?"
          } //alloy
        ],
        "TypeExceptionRegex": "Authenticat[a-z]+|Pool|Credential|GSS|Authoriz[a-z]+"
      },

      {
        "TypeName": "PermissionsError",
        "Exceptions": [
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "not part of .* Write service|access denied"
          }, //not part of write service is alloy, access denied is external
          {
            "ExceptionName": "SnowflakeSQLException",
            "MessageRegex": "no default role has been assigned to the user|session does not have a current database|no active warehouse selected in the current session|Role .* specified in the connect string is not granted to this user"
          }, //external
          {
            "ExceptionName": "SQLException",
            "MessageRegex": "permission denied|access denied"
          }, //external
          {
            "ExceptionName": "FailureException",
            "MessageRegex": "access denied"
          } //external
        ],
        "TypeExceptionRegex": "Permission|Access"
      }
    ],
    "Keywords": ["login", "kerberos", "credential", "username", "password", "authenticat[a-z]+", "permission", "initialize pool", "ticket", "GSSSO"]
  },



  {
    "CategoryName": "UserExecutionError",
    "Types": [
      {
        "TypeName": "QueryError",
        "Exceptions": [
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Can't find a match for function"
          }, //engine
          {
            "ExceptionName": "SnowflakeSQLException",
            "MessageRegex": "sql compilation error.*object.*does not exist or not authorized"
          }, //external
          {
            "ExceptionName": "AvaticaSqlException",
            "MessageRegex": "not entitled to data store"
          }, //external
          {
            "ExceptionName": "SQLException",
            "MessageRegex": "Table .* doesn't exist|(Column|Table) .* not found|User ID '.*' does not exist"
          }, //external
          {
            "ExceptionName": "JdbcSQLSyntaxErrorException",
            "MessageRegex": "(Table|Schema|[a-zA-Z]+) .* not found; SQL statement:"
          }, //external
          {
            "ExceptionName": "RedshiftException",
            "MessageRegex": "Error: relation .* does not exist"
          } //external
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "DatabaseNotFoundError",
        "Exceptions": [
          {
            "ExceptionName": "SQLSyntaxErrorException",
            "MessageRegex": "unknown (database|column)"
          }, //external
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Can't find database"
          }  // engine
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "UserRequestError",
        "Exceptions": [
          {
            "ExceptionName": "IllegalArgumentException",
            "MessageRegex": "No service found with uri"
          } //alloy
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "ServiceUpdateError",
        "Exceptions": [
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "new data for the service doesn't have the right pattern"
          }, //alloy
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "service must have more than one owner|test does not match execution type|Supported service return types are .* The return type of the provided service is"
          } //alloy
        ],
        "TypeExceptionRegex": ""
      }

    ],
    "Keywords": ["[a-zA-Z]* '.*' not found"]
  },



  {
    "CategoryName": "InternalServerError",
    "Types": [
      {
        "TypeName": "MissingItemError",
        "Exceptions": [
          {
            "ExceptionName": "WebApplicationException",
            "MessageRegex": "no registration found"
          }, //external
          {
            "ExceptionName": "RefreshFailedException",
            "MessageRegex": "unexpected"
          }, //external
          {
            "ExceptionName": "ReflectionsException",
            "MessageRegex": "could not get type for name"
          }, //external
          {
            "ExceptionName": "NotFoundException",
            "MessageRegex": "HTTP 404 Not Found"
          } //external
        ],
        "TypeExceptionRegex": "Missing|NotFound"
      },

      {
        "TypeName": "APIError",
        "Exceptions": [
          {
            "ExceptionName": "IOException",
            "MessageRegex": "Server returned HTTP response code: 500 for URL|Unable to tunnel through proxy. Proxy returns.*503 Service Unavailable"
          }, //external
          {
            "ExceptionName": "AWSSecurityTokenServiceException",
            "MessageRegex": "SkyBroker returned HTTP 403"
          } //alloy
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "JavaError",
        "Exceptions": [
          {
            "ExceptionName": "InterruptedException",
            "MessageRegex": ""
          } //external
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "ServerOverloadError",
        "Exceptions": [
          {
            "ExceptionName": "SQLException",
            "MessageRegex": "Insufficient buffers for '.*"
          } //external
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "ConfigurationError",
        "Exceptions": [
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "has not been configured properly"
          } //engine
        ],
        "TypeExceptionRegex": "Config[a-z]*"
      },

      {
        "TypeName": "IOError",
        "Exceptions": [
          {
            "ExceptionName": "ZipException",
            "MessageRegex": "ZipFile invalid LOC header"
          } //external
        ],
        "TypeExceptionRegex": "IO"
      }
    ],
    "Keywords": ["proxy","buffers"]
  },



  {
    "CategoryName": "ServerExecutionError",
    "Types": [

      {
        "TypeName": "DatabaseError",
        "Exceptions": [
          {
            "ExceptionName": "JdbcSQLIntegrityConstraintViolationException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "JdbcSQLSyntaxErrorException",
            "MessageRegex": "Syntax error in SQL statement"
          },//external
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "Redshift"
          },//external
          {
            "ExceptionName": "MongoCommandException",
            "MessageRegex": "changed during processing"
          },//external
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "reading GridFS|writing to the Stream"
          },//external
          {
            "ExceptionName": "JdbcSQLDataException",
            "MessageRegex": "Value too long for column"
          },//external
          {
            "ExceptionName": "AvaticaSqlException",
            "MessageRegex": "remote driver error"
          },//external
          {
            "ExceptionName": "ForbiddenException",
            "MessageRegex": "not entitled to data store"
          },//external
          {
            "ExceptionName": "IllegalArgumentException",
            "MessageRegex": "invalid hexadecimal representation of an ObjectId"
          },//external
          {
            "ExceptionName": "SQLException",
            "MessageRegex": "Cannot use view '.*' because it is invalid|Data exception - data type conversion is not possible"
          }//external
        ],
        "TypeExceptionRegex": "SQL"
      },

      {
        "TypeName": "GrammarToJSONConversionError",
        "Exceptions": [
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Unexpected (character|token)|no viable alternative at input|Missing table or alias for column|Bracket operation is not supported|Field '.*' is required"
          } //unexpected token, missing table or alias for column, bracket operation not supported, field xyz is required - engine. unexpected character, no viable alternative at input - external,
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "PureError",
        "Exceptions": [
          {
            "ExceptionName": "PureExecutionException",
            "MessageRegex": "Execution error at .*(cast exception|ERROR unhandled type for value)|cannot cast [a ]?collection of size 0 to multiplicity"
          }, //cannot cast [a]? collection of size.. is engine, rest is external?
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Engine was unable to load information from the Pure SDLC|Can't find mapping|Assert failure at"
          }  //engine was unable, can't find mapping - engine, assert failure at - external
        ],
        "TypeExceptionRegex": "Pure"
      },

      {
        "TypeName": "JSONError",
        "Exceptions": [
          {
            "ExceptionName": "JsonParseException",
            "MessageRegex": "Unexpected (character|token)"
          }, //token - engine, character - external
          {
            "ExceptionName": "UnrecognizedPropertyException",
            "MessageRegex": "Unrecognised field.*not marked as ignorable|.*"
          }, //external
          {
            "ExceptionName": "InvalidTypeIdException",
            "MessageRegex": "Could not resolve type id.*as a subtype of|Missing type id when trying to resolve subtype of"
          }, //external
          {
            "ExceptionName": "InvalidDefinitionException",
            "MessageRegex": "Direct self-reference leading to cycle|.*"
          } //external
        ],
        "TypeExceptionRegex": "JSON"
      },

      {
        "TypeName": "GraphError",
        "Exceptions": [
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Error in.*Can't (find [the ]?(property|store|type|profile|packageable element|Connection|SchemaSet|table.*in schema.*and database.*)|build the message function for constraint .* of class)"
          }, //build the message function for constraint .* of class) - external, rest is engine
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Error in.*[all required service parameters should be mapped|Mapping error: the join .* does not contain the source table|Milestone column.*not found on table definition|Collection element must have a multiplicity|Execution error at]?"
          } //Milestone column.*not found on table definition and Collection element must have a multiplicity and all required service parameters should be mapped and mapping error - engine, execution error at is external
        ],
        "TypeExceptionRegex": "Graph"
      },

      {
        "TypeName": "JavaErrors",
        "Exceptions": [
          {
            "ExceptionName": "JavaCompileException",
            "MessageRegex": "incompatible type"
          },//external
          {
            "ExceptionName": "ClassCastException",
            "MessageRegex": ""
          },//external
          {
            "ExceptionName": "NonStringOrTemplateOutputException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "IllegalArgumentException",
            "MessageRegex": "Missing external parameter"
          }, //engine
          {
            "ExceptionName": "EngineException",
            "MessageRegex": "Can't find property .* in (class|association)"
          } //engine
        ],
        "TypeExceptionRegex": ""
      },

      {
      "TypeName": "ServiceRequestError",
      "Exceptions": [
        {
          "ExceptionName": "IllegalArgumentException",
          "MessageRegex": "Error loading service|Invalid provided parameter|Reprocessing sql failed with vars"
        }, //invalid provided parameter and reprocessing sql failed with vars - engine; error loading service - external
        {
          "ExceptionName": "RuntimeException",
          "MessageRegex": "HTTP request.*failed with error|Invalid Input: null|Input stream was not provided|The following PackageableElementPointers.*do not exist in the project data loaded from the metadata server"
        }, //invalid input - alloy, rest is engine
        {
          "ExceptionName": "EngineException",
          "MessageRegex": "Can't resolve the builder for function|Can't find model for ID|No generation found with id|Can't find service"
        } //can't resolve the builder, can't find service - engine, can't find model, no generation found with id - alloy
      ],
      "TypeExceptionRegex": ""
      },

      {
        "TypeName": "SlangError",
        "Exceptions": [
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "slang exception"
          } //none ??? delete from OS
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "FreemarkerError",
        "Exceptions": [
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "Issue processing freemarker function|MiscTemplateException"
          }, //issue processing freemarker - engine, misctemplateexception - external
          {
            "ExceptionName": "_MiscTemplateException",
            "MessageRegex": "When calling function.*required parameter.*was specified, but had null/missing value"
          }, //external
          {
            "ExceptionName": "StopException",
            "MessageRegex": "no metadata found"
          } //external
        ],
        "TypeExceptionRegex": ""
      },

      {
        "TypeName": "RegexError",
        "Exceptions": [
          {
            "ExceptionName": "PatternSyntaxException",
            "MessageRegex": "Illegal repetition"
          } // external
        ],
        "TypeExceptionRegex": ""
      }

    ],
    "Keywords": ["mapping error","Error in '.*::.*':" ]
  },



  {
    "CategoryName": "OtherError",
    "Types": [

      {
        "TypeName": "ConnectionError",
        "Exceptions": [
          {
            "ExceptionName": "ConnectionException",
            "MessageRegex": ""
          }, //engine
          {
            "ExceptionName": "SQLTransientConnectionException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "SocketTimeoutException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "MappableException",
            "MessageRegex": ""
          }, //external
          {
            "ExceptionName": "EOFException",
            "MessageRegex": "unexpected end of stream"
          }, //external
          {
            "ExceptionName": "SQLException",
            "MessageRegex": "Connection was terminated"
          } //external
        ],
        "TypeExceptionRegex": "Connection|Timeout"
      },

      {
        "TypeName": "TestingError",
        "Exceptions": [
          {
            "ExceptionName": "IllegalArgumentException",
            "MessageRegex": "Error running tests"
          }, //external
          {
            "ExceptionName": "RuntimeException",
            "MessageRegex": "Checked exception caught in Procedure"
          }, //external
          {
            "ExceptionName": "PureAssertFailException",
            "MessageRegex": "exception occurred executing service test suites|Assert failure at*trees are not supported yet|.*"
          } //exception occured executing service test suites - engine, assert failure at - external
        ],
        "TypeExceptionRegex": ""
      }
    ],
    "Keywords": ["test|timeout"]
  }
]
